### PR TITLE
docs: added the Webiny integration details

### PR DESCRIPTION
**Pull request by swapnilmmane**
[Webiny](https://www.webiny.com/) is Open-Source Serverless Enterprise CMS.  
Its GraphQL APIs can be accessed using remote schemas in Hasura. 
Added the instructions on how to access the APIs using the Remote Schemas feature.

### CODE REVIEW

**Comment by praveenweb** [comment]
Hey @swapnilmmane - This is great! Let me review this the coming week and take this forward :)

**Review by praveenweb — APPROVED** [review]

**Comment by swapnilmmane** [comment]
Thank you so much @praveenweb for the review and merge! :) 

Just would like to know, is there any preview instance available where I can see the changes before merging (i.e. once a PR is created, is there any way I can see the preview).

Also, if I would like to add some images in the instructions, can I create an `asset` folder inside [webiny](https://github.com/hasura/data-hub/tree/main/remote-schemas/webiny) directory and reference the image resources from here.

**Comment by praveenweb** [comment]
@swapnilmmane - I can try to set up a simple Netlify PR app to have a preview instance.

For images, you can upload them inside an asset folder and create the PR, but we will be moving them to a CDN to keep the repo lightweight.

**Comment by swapnilmmane** [comment]
sounds great, thank you @praveenweb! :)

**Pull request merged**
